### ISSUE TITLE
Differences in the font and SVG icons

### ISSUE THREAD

**Issue by zdravkov** [telerik/kendo-icons#62]
Currently there are differences between some font and SVG icons - here is a demo - https://stackblitz.com/edit/react-1h2qnn?file=app%2Fmain.tsx

Some are missing like 'arrows-left-right-icon' and some are different like 'gap-column-icon' .

**Comment by TeyaVes** [comment]
This is hapenning because the font icons currently part of the kendo-themes differentiate slightly from the SVG icons - there are renamed or missing icons. However, once we start using the kendo-icons package in all SASS themes (currently used only in the Fluent theme), which is planned for the January release, the issue will be fixed:
[https://stackblitz.com/edit/react-1h2qnn-axrtlo?file=index.html](https://stackblitz.com/edit/react-1h2qnn-axrtlo?file=index.html
)
